//! Generated-UI cache store (design doc §6): `.cache/mdpeek/<hash>.gui.json`.
//!
//! The store is a thin content-addressed layer: key by [`content_hash`], write
//! a [`GuiCacheEntry`] as JSON, read it back on a hit. Invalidation is implicit
//! — a changed document / generator / schema produces a different key (see
//! `key.rs`), so stale entries are simply never looked up again.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::ir::{SourceRange, UiNode};

use super::key::{SCHEMA_VERSION, content_hash};

/// A cached generation result (design §4.3). `block_classification` from the
/// design lives in Layer 2's `model`; it's added here once that lands.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GuiCacheEntry {
    /// Document type as classified upstream (`"generic"` until Layer 2 lands).
    pub document_type: String,
    pub ui_ir: Vec<UiNode>,
    /// Flattened list of every verified source range, for quick lookup.
    pub source_ranges: Vec<SourceRange>,
    /// Overall confidence (min of node confidences; 1.0 for pure rules).
    pub confidence: f32,
    /// Generator id: `"rules"` | `"claude-…"`.
    pub model: String,
    /// Unix epoch seconds when generated. (RFC3339 formatting deferred to avoid
    /// a date dependency; this is an internal cache field.)
    pub generated_at: u64,
    pub content_hash: String,
    pub schema_version: u32,
}

impl GuiCacheEntry {
    pub fn new(document_type: String, ui_ir: Vec<UiNode>, model: String, content_hash: String) -> Self {
        let source_ranges = collect_ranges(&ui_ir);
        let confidence = overall_confidence(&ui_ir);
        GuiCacheEntry {
            document_type,
            ui_ir,
            source_ranges,
            confidence,
            model,
            generated_at: now_unix(),
            content_hash,
            schema_version: SCHEMA_VERSION,
        }
    }
}

fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn collect_ranges(nodes: &[UiNode]) -> Vec<SourceRange> {
    let mut out = Vec::new();
    for n in nodes {
        if let Some(r) = n.meta().source_range {
            out.push(r);
        }
        if let UiNode::Tabs(t) = n {
            for tab in &t.tabs {
                out.extend(collect_ranges(&tab.children));
            }
        }
    }
    out
}

fn overall_confidence(nodes: &[UiNode]) -> f32 {
    nodes
        .iter()
        .filter_map(|n| n.meta().confidence)
        .fold(1.0f32, f32::min)
}

/// On-disk cache rooted at `<root>/.cache/mdpeek`.
pub struct CacheStore {
    dir: PathBuf,
}

impl CacheStore {
    /// Create a store under `root` (typically the current working directory).
    pub fn new(root: impl AsRef<Path>) -> Self {
        CacheStore {
            dir: root.as_ref().join(".cache").join("mdpeek"),
        }
    }

    fn path_for(&self, hash: &str) -> PathBuf {
        self.dir.join(format!("{hash}.gui.json"))
    }

    /// Look up a cached entry for `markdown` generated by `model_id`. `filename`
    /// participates in the key (it can change the inferred document type).
    pub fn get(
        &self,
        markdown: &str,
        model_id: &str,
        filename: Option<&str>,
    ) -> Option<GuiCacheEntry> {
        let hash = content_hash(markdown, model_id, filename);
        let bytes = std::fs::read(self.path_for(&hash)).ok()?;
        let entry: GuiCacheEntry = serde_json::from_slice(&bytes).ok()?;
        // Guard against a schema bump slipping through (belt-and-braces; the key
        // already encodes SCHEMA_VERSION).
        if entry.schema_version == SCHEMA_VERSION {
            Some(entry)
        } else {
            None
        }
    }

    /// Persist `entry`, returning its content hash / filename stem.
    pub fn put(&self, entry: &GuiCacheEntry) -> Result<String> {
        std::fs::create_dir_all(&self.dir)
            .with_context(|| format!("creating cache dir {}", self.dir.display()))?;
        let path = self.path_for(&entry.content_hash);
        let json = serde_json::to_vec_pretty(entry).context("serializing cache entry")?;
        std::fs::write(&path, json).with_context(|| format!("writing {}", path.display()))?;
        Ok(entry.content_hash.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::node::*;

    fn sample_nodes() -> Vec<UiNode> {
        vec![UiNode::Callout(CalloutNode {
            meta: NodeMeta {
                source_range: Some(SourceRange {
                    start_line: 1,
                    start_column: 1,
                    end_line: 2,
                    end_column: 1,
                }),
                confidence: Some(0.9),
                ..Default::default()
            },
            severity: Severity::Info,
            title: None,
            body: "hi".into(),
        })]
    }

    #[test]
    fn roundtrip_put_get() {
        let tmp = tempfile::tempdir().unwrap();
        let store = CacheStore::new(tmp.path());
        let md = "# Doc\n\ncontent\n";
        let hash = content_hash(md, "rules", None);
        let entry = GuiCacheEntry::new("generic".into(), sample_nodes(), "rules".into(), hash);
        store.put(&entry).unwrap();

        let got = store.get(md, "rules", None).expect("cache hit");
        assert_eq!(got.ui_ir.len(), 1);
        assert_eq!(got.source_ranges.len(), 1);
        assert!((got.confidence - 0.9).abs() < 1e-6);
    }

    #[test]
    fn miss_on_different_content() {
        let tmp = tempfile::tempdir().unwrap();
        let store = CacheStore::new(tmp.path());
        assert!(store.get("nothing cached", "rules", None).is_none());
    }
}
